name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - develop

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Set environment variables
        run: |
          if [ "${GITHUB_REF_NAME}" == "main" ]; then
            echo "AWS_REGION=${{ secrets.AWS_PRD_REGION }}" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY=${{ secrets.AWS_PRD_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_KEY=${{ secrets.AWS_PRD_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
            echo "S3_BUCKET=${{ secrets.AWS_CDK_PRD_S3 }}" >> $GITHUB_ENV
            echo "WORKSPACE=prd" >> $GITHUB_ENV
          else
            echo "AWS_REGION=${{ secrets.AWS_DEV_REGION }}" >> $GITHUB_ENV
            echo "AWS_ACCESS_KEY=${{ secrets.AWS_DEV_ACCESS_KEY_ID }}" >> $GITHUB_ENV
            echo "AWS_SECRET_KEY=${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
            echo "S3_BUCKET=${{ secrets.AWS_CDK_DEV_S3 }}" >> $GITHUB_ENV
            echo "WORKSPACE=dev" >> $GITHUB_ENV
          fi

      - name: Export AWS credentials for CLI
        run: |
          export AWS_REGION=$AWS_REGION
          export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
          export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY

      - name: Check if S3 bucket has Terraform state
        id: check_bucket
        run: |
          if aws s3 ls s3://$S3_BUCKET/ | grep -q .; then
            echo "Bucket já tem Terraform state, pulando bootstrap"
            echo "RUN_BOOTSTRAP=false" >> $GITHUB_ENV
          else
            echo "Bucket vazio, rodando bootstrap"
            echo "RUN_BOOTSTRAP=true" >> $GITHUB_ENV
          fi

      - name: Terraform Init & Apply Bootstrap
        if: env.RUN_BOOTSTRAP == 'true'
        working-directory: bootstrap
        run: |
          terraform init -reconfigure
          terraform apply -auto-approve -var="aws_region=$AWS_REGION" -var="aws_access_key=$AWS_ACCESS_KEY" -var="aws_secret_key=$AWS_SECRET_KEY" -var="stage=$WORKSPACE"

      - name: Terraform Init Main
        working-directory: .
        run: terraform init -reconfigure -backend-config="bucket=${S3_BUCKET}" -backend-config="key=terraform.tfstate" -backend-config="region=${AWS_REGION}" -backend-config="dynamodb_table=${WORKSPACE}-terraform-locks" -backend-config="encrypt=true"

      - name: Select or Create Workspace
        working-directory: .
        run: terraform workspace select "$WORKSPACE" || terraform workspace new "$WORKSPACE"

      - name: Terraform Plan
        working-directory: .
        run: terraform plan -var="stage=$WORKSPACE" -var="aws_region=$AWS_REGION" -var="aws_access_key=$AWS_ACCESS_KEY" -var="aws_secret_key=$AWS_SECRET_KEY" -var="s3_bucket=$S3_BUCKET"

      - name: Terraform Apply
        working-directory: .
        run: terraform apply -auto-approve -var="stage=$WORKSPACE" -var="aws_region=$AWS_REGION" -var="aws_access_key=$AWS_ACCESS_KEY" -var="aws_secret_key=$AWS_SECRET_KEY" -var="s3_bucket=$S3_BUCKET"
