name: Deploy Dev Stack

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_DEV_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_SECRET_ACCESS_KEY }}
      AWS_CDK_S3_BUCKET: ${{ secrets.AWS_CDK_DEV_S3 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: yarn install

      - name: Build TypeScript
        run: yarn build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy CDK Stack (Dev)
        run: |
          cdk bootstrap \
            --bootstrap-bucket-name $AWS_CDK_S3_BUCKET \
            aws://$AWS_ACCOUNT_ID/$AWS_REGION
          cdk deploy --context stage=dev --require-approval never --app "npx ts-node bin/infra.ts" --region $AWS_REGION
